### ISSUE TITLE
Project Programmer fails to compile

### ISSUE THREAD

**Issue by aborisovich** [KokoSoft/Programmer#1]
**Description**
Building the Programmer project with error:
```
Programmer\TargetTester.cpp(448,16): error C2039: 'status': is not a member of 'ETarget'
Programmer\Programmer.hpp(21,7): message : see declaration of 'ETarget'
```
**Repro steps**
1) Build solution

**Environment**
Visual Studio 2022
C++ ver: /std:c++latest
Tested commit: 211c74d1f14c6585e94b28bed1e976f73730ffb9

**Comment by KokoSoft** [comment]
The problem is caused because I'm not commited a changes in the `Programmer.h`. This project is in the early stages of development, and I'm quite not following the rules. I promise to behave better :)
